function Aon=mathieu_B(n,q,nmax)
if length(n)==1
if rem(n,2)==0
    m=[2:2:2*nmax+2];
    diagm=diag(m.^2);
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aoe,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aoe=Aoe(:,srt);
    Reg=sum(Aoe.^2,1);
    Reg=repmat(Reg,nmax+1,1);
    Aoe=Aoe./Reg;
    Aon=Aoe(:,n/2);
else
    m=[1:2:2*nmax+1];
    diagm=diag(m.^2);
    diagm(1,1)=diagm(1,1)-q;
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aoo,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aoo=Aoo(:,srt);
    Reg=sum(Aoo.^2,1);
    Reg=repmat(Reg,nmax+1,1);
    Aoo=Aoo./Reg;
    Aon=Aoo(:,(n+1)/2);
end
else
    n=n.';
    m=[2:2:2*nmax+2];
    diagm=diag(m.^2);
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aoe,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aoe=Aoe(:,srt);
    Reg=sum(Aoe.^2,1);
    Reg=repmat(Reg,nmax+1,1);
    Aoe=Aoe./Reg;
    Ao(:,m+1)=Aoe;
    m=[1:2:2*nmax+1];
    diagm=diag(m.^2);
    diagm(1,1)=diagm(1,1)-q;
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aoo,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aoo=Aoo(:,srt);
    Reg=sum(Aoo.^2,1);
    Reg=repmat(Reg,nmax+1,1);
    Aoo=Aoo./Reg;
    Ao(:,m+1)=Aoo;
    Aon=Ao(:,n+1);
end