function Aen=mathieu_A(n,q,nmax)
if length(n)==1
if rem(n,2)==0
    m=[0:2:2*nmax];
    diagm=diag(m.^2);
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    qvector(1)=qvector(1).*2;
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aee,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aee=Aee(:,srt);
    Reg=sum(Aee.^2,1)+Aee(1,:).^2;
    Reg=repmat(Reg,nmax+1,1);
%     Reg=Reg.'*sign(Aee(1,:));
    Aee=Aee./sqrt(abs(Reg))*sign(Aee(1,1));
    Aen=Aee(:,n/2+1);
else
    m=[1:2:2*nmax+1];
    diagm=diag(m.^2);
    diagm(1,1)=diagm(1,1)+q;
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aeo,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aeo=Aeo(:,srt);
    Reg=sum(Aeo.^2,1);
    Reg=repmat(Reg,nmax+1,1);
    Aeo=Aeo./Reg;
    Aen=Aeo(:,(n+1)/2);
end
else
    n=n.';
    m=[0:2:2*nmax];
    diagm=diag(m.^2);
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    qvector(1)=qvector(1).*2;
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aee,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aee=Aee(:,srt);
    Reg=sum(Aee.^2,1)+Aee(1,:).^2;
    Reg=repmat(Reg,nmax+1,1);
%     Reg=Reg.'*sign(Aee(1,:));
    Aee=Aee./sqrt(abs(Reg))*sign(Aee(1,1));
    Ae(:,m+1)=Aee;
    m=[1:2:2*nmax+1];
    diagm=diag(m.^2);
    diagm(1,1)=diagm(1,1)+q;
    qvector=q*ones(1,nmax);
    diagu=diag(qvector,1);
    diagd=diag(qvector,-1);
    M=diagm+diagu+diagd;
    [Aeo,a]=eig(M,'nobalance');
    [a,srt]=sort(diag(a));
    Aeo=Aeo(:,srt);
    Reg=sum(Aeo.^2,1);
    Reg=repmat(Reg,nmax+1,1);
    Aeo=Aeo./Reg;
    Ae(:,m+1)=Aeo;
    Aen=Ae(:,n+1);
end